/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Snake;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author tret
 */
public class MainFrame extends javax.swing.JFrame {
    private final Conf conf;
    private final Board board;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(Conf conf) {
        this.conf = conf;
        
        //initComponents();
        init();
        board = new Board(conf);
        add(board);
        
        setResizable(false);
        pack();
        
        setTitle("Snake - " + conf.readUser());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar = new javax.swing.JMenuBar();
        exitMenu = new javax.swing.JMenu();
        restartMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitMenu.setText("Вихід");
        menuBar.add(exitMenu);

        restartMenu.setText("Перезапуск");
        menuBar.add(restartMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        menuBar = new javax.swing.JMenuBar();
        exitMenu = new javax.swing.JMenu();
        //exitMenuItem = new javax.swing.JMenuItem();
        restartMenu = new javax.swing.JMenu();
        //restartMenuItem = new javax.swing.JMenuItem();

        exitMenu.setText("Файл");

        exitMenu.setText("Вихід");
        exitMenu.addMenuListener(new MenuListener() {
            @Override
            public void menuSelected(MenuEvent evt) {
                System.out.println("Before exit.");
                System.exit(0);
            }
            
            @Override
            public void menuCanceled(MenuEvent evt) {}
            @Override
            public void menuDeselected(MenuEvent evt) {}
        });
        //exitMenu.add(exitMenuItem);

        menuBar.add(exitMenu);

        restartMenu.setText("Перезапуск");
        menuBar.add(restartMenu);

        //restartMenuItem.setText("Перезапуск");
        restartMenu.addMenuListener(new MenuListener() {
            public void menuSelected(MenuEvent evt) {
                board.initGame();
            }
            
            @Override
            public void menuCanceled(MenuEvent evt) {
            }
            @Override
            public void menuDeselected(MenuEvent evt) {
            }
        });
        //restartMenu.add(restartMenuItem);

        menuBar.add(restartMenu);

        setJMenuBar(menuBar);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(new Conf()).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu exitMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu restartMenu;
    // End of variables declaration//GEN-END:variables
}
